-- MySQL Script generated by MySQL Workbench
-- Fri Mar  2 14:12:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Klasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Klasse` (
  `idKlasse` INT NOT NULL,
  `Klassenname` VARCHAR(45) NULL,
  PRIMARY KEY (`idKlasse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL,
  `S_vn` VARCHAR(45) NULL,
  `S_nn` VARCHAR(45) NULL,
  `Klasse_idKlasse` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  CONSTRAINT `fk_Student_Klasse1`
    FOREIGN KEY (`Klasse_idKlasse`)
    REFERENCES `mydb`.`Klasse` (`idKlasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Student_Klasse1_idx` ON `mydb`.`Student` (`Klasse_idKlasse` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Lehrer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lehrer` (
  `idLehrer` INT NOT NULL,
  `L_vn` VARCHAR(45) NULL,
  `L_nn` VARCHAR(45) NULL,
  PRIMARY KEY (`idLehrer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bewertung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bewertung` (
  `idBewertung` INT NOT NULL,
  `FrageNR` INT NOT NULL,
  `FrageWert` INT NULL,
  PRIMARY KEY (`idBewertung`, `FrageNR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modulname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modulname` (
  `idModulnr` INT NOT NULL,
  `Modulname` VARCHAR(45) NULL,
  PRIMARY KEY (`idModulnr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terminplan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Terminplan` (
  `Student_idStudent` INT NOT NULL,
  `Lehrer_idLehrer` INT NOT NULL,
  `Modulnr_idModulnr` INT NOT NULL,
  `Bewertung_idBewertung` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Lehrer_idLehrer`, `Bewertung_idBewertung`),
  CONSTRAINT `fk_Student_has_Lehrer_Student`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Lehrer_Lehrer1`
    FOREIGN KEY (`Lehrer_idLehrer`)
    REFERENCES `mydb`.`Lehrer` (`idLehrer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modul_Modulnr1`
    FOREIGN KEY (`Modulnr_idModulnr`)
    REFERENCES `mydb`.`Modulname` (`idModulnr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terminplan_Bewertung1`
    FOREIGN KEY (`Bewertung_idBewertung`)
    REFERENCES `mydb`.`Bewertung` (`idBewertung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Student_has_Lehrer_Lehrer1_idx` ON `mydb`.`Terminplan` (`Lehrer_idLehrer` ASC);

CREATE INDEX `fk_Student_has_Lehrer_Student_idx` ON `mydb`.`Terminplan` (`Student_idStudent` ASC);

CREATE INDEX `fk_Modul_Modulnr1_idx` ON `mydb`.`Terminplan` (`Modulnr_idModulnr` ASC);

CREATE INDEX `fk_Terminplan_Bewertung1_idx` ON `mydb`.`Terminplan` (`Bewertung_idBewertung` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`bewertungText`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bewertungText` (
  `B_ID` INT NOT NULL,
  `Pos` VARCHAR(45) NULL,
  `Neg` VARCHAR(45) NULL,
  `Bewertung_idBewertung` INT NOT NULL,
  PRIMARY KEY (`B_ID`),
  CONSTRAINT `fk_bewertungText_Bewertung1`
    FOREIGN KEY (`Bewertung_idBewertung`)
    REFERENCES `mydb`.`Bewertung` (`idBewertung`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bewertungText_Bewertung1_idx` ON `mydb`.`bewertungText` (`Bewertung_idBewertung` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
